StudyReg.Web/Models/Deck.cs
using StudyReg.Web.Areas.Identity.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudyReg.Web.Models
{
    public class Deck
    {
        public int Id { get; set; }

        public string Title { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime Created { get; set; }

        [ForeignKey("UserId")]
        public StudyRegWebUser User { get; set; }
        public ICollection<DeckCard> Cards { get; set; }
    }
}

StudyReg.Web/Pages/Cards/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudyReg.Web.Areas.Identity.Data;
using StudyReg.Web.Data;
using StudyReg.Web.Models;

namespace StudyReg.Web.Pages.Cards
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<StudyRegWebUser> _userManager;

        public CreateModel(StudyReg.Web.Data.ApplicationDbContext context, UserManager<StudyRegWebUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Card Card { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Card.User = await _userManager.GetUserAsync(HttpContext.User);

            _context.Card.Add(Card);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

StudyReg.Web/Pages/Cards/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyReg.Web.Areas.Identity.Data;
using StudyReg.Web.Data;
using StudyReg.Web.Models;

namespace StudyReg.Web.Pages.Cards
{
    public class DeleteModel : PageModel
    {
        private readonly StudyReg.Web.Data.ApplicationDbContext _context;
        private readonly UserManager<StudyRegWebUser> _userManager;

        public DeleteModel(StudyReg.Web.Data.ApplicationDbContext context, UserManager<StudyRegWebUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [BindProperty]
        public Card Card { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);

            Card = await _context.Card.FirstOrDefaultAsync(m => m.Id == id && m.User.Id == user.Id);

            if (Card == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);

            Card = await _context.Card.FirstOrDefaultAsync(m => m.Id == id && m.User.Id == user.Id);

            if (Card != null)
            {
                _context.Card.Remove(Card);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

StudyReg.Web/Pages/Cards/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyReg.Web.Areas.Identity.Data;
using StudyReg.Web.Data;
using StudyReg.Web.Models;

namespace StudyReg.Web.Pages.Cards
{
    public class DetailsModel : PageModel
    {
        private readonly StudyReg.Web.Data.ApplicationDbContext _context;
        private readonly UserManager<StudyRegWebUser> _userManager;

        public DetailsModel(StudyReg.Web.Data.ApplicationDbContext context, UserManager<StudyRegWebUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public Card Card { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);

            Card = await _context.Card.FirstOrDefaultAsync(m => m.Id == id && m.User.Id == user.Id);

            if (Card == null)
            {
                return NotFound();
            }

            return Page();
        }
    }
}

StudyReg.Web/Pages/Cards/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyReg.Web.Areas.Identity.Data;
using StudyReg.Web.Data;
using StudyReg.Web.Models;

namespace StudyReg.Web.Pages.Cards
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<StudyRegWebUser> _userManager;

        public EditModel(ApplicationDbContext context, UserManager<StudyRegWebUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [BindProperty]
        public Card Card { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);

            Card = await _context.Card.FirstOrDefaultAsync(m => m.Id == id && m.User.Id == user.Id);

            if (Card == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Card).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CardExists(Card.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CardExists(int id)
        {
            return _context.Card.Any(e => e.Id == id);
        }
    }
}

StudyReg.Web/Pages/Decks/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudyReg.Web.Areas.Identity.Data;
using StudyReg.Web.Data;
using StudyReg.Web.Models;

namespace StudyReg.Web.Pages.Decks
{
    public class CreateModel : PageModel
    {
        private readonly StudyReg.Web.Data.ApplicationDbContext _context;
        private readonly UserManager<StudyRegWebUser> _userManager;

        public CreateModel(StudyReg.Web.Data.ApplicationDbContext context, UserManager<StudyRegWebUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Deck Deck { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Deck.Created = DateTime.UtcNow;
            Deck.User = await _userManager.GetUserAsync(HttpContext.User);

            _context.Deck.Add(Deck);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

StudyReg.Web/Pages/Decks/Manage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyReg.Web.Areas.Identity.Data;
using StudyReg.Web.Data;
using StudyReg.Web.Models;

namespace StudyReg.Web.Pages.Decks
{
    public class ManageModel : PageModel
    {
        private readonly StudyReg.Web.Data.ApplicationDbContext _context;
        private readonly UserManager<StudyRegWebUser> _userManager;

        public ManageModel(StudyReg.Web.Data.ApplicationDbContext context, UserManager<StudyRegWebUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [BindProperty]
        public Deck Deck { get; set; }

        public IList<DeckCard> DeckCards {get; set;}

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);

            Deck = await _context.Deck
                .FirstOrDefaultAsync(m => m.Id == id && m.User.Id == user.Id);

            if (Deck == null)
            {
                return NotFound();
            }

            DeckCards = await _context.DeckCard
                .Include(m => m.Card)
                .Where(m => m.DeckId == Deck.Id)
                .ToListAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Deck).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DeckExists(Deck.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostDelete(int cardId, int deckId)
        {
            var deckCard = await _context.DeckCard.FindAsync(cardId, deckId);

            if (deckCard != null)
            {
                _context.DeckCard.Remove(deckCard);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Manage", new { id = deckId });
        }

        public async Task<IActionResult> OnPostAdd(int deckId, string cardTitle, string cardAnswer)
        {
            if (string.IsNullOrWhiteSpace(cardTitle) || string.IsNullOrWhiteSpace(cardAnswer))
            {
                return RedirectToPage("./Manage", new { id = deckId });
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);

            Deck = await _context.Deck.FirstOrDefaultAsync(m => m.Id == deckId && m.User.Id == user.Id);

            if (Deck == null)
            {
                return RedirectToPage("./Manage", new { id = deckId });
            }

            var card = new Card()
            {
                Title = cardTitle,
                Answer = cardAnswer,
                User = user
            };

            _context.Card.Add(card);
            await _context.SaveChangesAsync();

            var deckCard = new DeckCard() { CardId = card.Id, DeckId = deckId };
            _context.Add(deckCard);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Manage", new { id = deckId });
        }

        private bool DeckExists(int id)
        {
            return _context.Deck.Any(e => e.Id == id);
        }
    }
}

StudyReg.Web/Pages/Decks/Study.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyReg.Web.Areas.Identity.Data;
using StudyReg.Web.Data;
using StudyReg.Web.Models;

namespace StudyReg.Web.Pages.Decks
{
    public class StudyModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<StudyRegWebUser> _userManager;

        private const int _lowestStage = 1;
        private const int _highestStage = 4;

        public StudyModel(StudyReg.Web.Data.ApplicationDbContext context, UserManager<StudyRegWebUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public Deck Deck { get; set; }

        public Card Card { get; set; }

        public List<(int Stage, int Count)> Stages { get; set; }

        public int Remaining { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);

            Deck = await _context.Deck.FirstOrDefaultAsync(m => m.Id == id && m.User.Id == user.Id);

            if (Deck == null)
            {
                return NotFound();
            }

            var recentLogs = await _context.Card
                .Where(c => c.Decks.Any(d => d.DeckId == id))
                .Select(c => c.Logs.OrderByDescending(l => l.Timestamp).FirstOrDefault())
                .ToListAsync();

            Stages = new List<(int Stage, int Count)>();

            for (var stage = 0; stage <= _highestStage; stage++)
            {
                var count = 0;
                if (stage == 0)
                    count = recentLogs.Where(l => l?.Stage == null).Count();
                else
                    count = recentLogs.Where(l => l?.Stage != null && l.Stage == stage).Count();

                Stages.Add((stage, count));
            }

            return Page();
        }

        public async Task<IActionResult> OnPostStart(int deckId, int stage, int numCards)
        {
            await SetNextCard(deckId, stage, numCards);
            Remaining = numCards - 1;
            return Page();
        }

        public async Task<IActionResult> OnPostAnswer(int deckId, int cardId, bool result, int cardsLeft)
        {
            Card = await _context.Card
                .Include(c => c.Logs)
                .FirstOrDefaultAsync(c => c.Id == cardId);

            var user = await _userManager.GetUserAsync(HttpContext.User);

            if (Card == null || user == null)
            {
                return NotFound();
            }

            var newLog = new StudyLog()
            {
                Result = result,
                Timestamp = DateTime.UtcNow,
                User = user,
                Card = Card
            };

            var mostRecentLog = Card.Logs
                .OrderByDescending(l => l.Timestamp)
                .FirstOrDefault();

            var currentStage = mostRecentLog?.Stage ?? 0;

            // If user got correct and previous log exist
            if (result && mostRecentLog != null)
            {
                if (mostRecentLog.Stage < _highestStage)
                    newLog.Stage = mostRecentLog.Stage + 1;
                else
                    newLog.Stage = _highestStage;
            }
            // Else the user got correct and no prior history,
            // Or the user got wrong - send to lowest stage
            else
            {
                newLog.Stage = _lowestStage;
            }

            _context.StudyLog.Add(newLog);
            await _context.SaveChangesAsync();

            // Get next card
            await SetNextCard(deckId, currentStage, cardsLeft);

            Remaining = cardsLeft - 1;

            if (Card == null)
                return RedirectToPage("./Study", new { id = deckId });

            return Page();
        }

        private async Task SetNextCard(int deckId, int stage, int cardsLeft)
        {
            Deck = await _context.Deck
                .FirstOrDefaultAsync(m => m.Id == deckId);

            if (cardsLeft <= 0)
            {
                Card = null;
                return;
            }
                
            if (stage != 0)
            {
                Card = await _context.Card
                    .Where(c => c.Decks.Any(d => d.DeckId == deckId) &&
                    c.Logs.OrderByDescending(l => l.Timestamp).FirstOrDefault().Stage == stage)
                    .OrderBy(c => c.Logs.OrderByDescending(l => l.Timestamp).FirstOrDefault().Timestamp)
                    .FirstOrDefaultAsync();
            }
            else
            {
                Card = await _context.Card
                    .Where(c => c.Decks.Any(d => d.DeckId == deckId) && !c.Logs.Any())
                    .FirstOrDefaultAsync();
            }
        }
    }
}

StudyReg.Web/Pages/Decks/Create.cshtml
@page
@model StudyReg.Web.Pages.Decks.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Deck</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Deck.Title" class="control-label"></label>
                <input asp-for="Deck.Title" class="form-control" />
                <span asp-validation-for="Deck.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudyReg.Web/Pages/Decks/Delete.cshtml
@page
@model StudyReg.Web.Pages.Decks.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Deck</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Deck.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Deck.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Deck.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Deck.Created)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Deck.Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

StudyReg.Web/Pages/Decks/Details.cshtml
@page
@model StudyReg.Web.Pages.Decks.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Deck</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Deck.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Deck.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Deck.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Deck.Created)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Deck.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

StudyReg.Web/Pages/Decks/Edit.cshtml
@page
@model StudyReg.Web.Pages.Decks.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Editing Deck</h2>
<div class="row">
    <div class="col-md-4">
        <form method="post" class="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Deck.Id" />
            <div class="form-group">
                <label asp-for="Deck.Title" class="control-label"></label>
                <input asp-for="Deck.Title" class="form-control" />
                <span asp-validation-for="Deck.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudyReg.Web/Pages/Decks/Index.cshtml
@page
@model StudyReg.Web.Pages.Decks.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Decks</h2>

<a class="btn btn-success pull-right" asp-page="Create"><i class="glyphicon glyphicon-plus"></i>&nbsp;New Deck</a>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Deck[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deck[0].Created)
            </th>
            <th>Cards</th>
            <th>Study</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Deck) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)&nbsp;<a asp-page="./Edit" asp-route-id="@item.Id">&nbsp;<i class="glyphicon glyphicon-pencil"></i></a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                <a class="btn btn-primary" asp-page="./Manage" asp-route-id="@item.Id">&nbsp;<i class="glyphicon glyphicon-pencil"></i>&nbsp;</a>
            </td>
            <td>
                <a class="btn btn-primary" asp-page="./Study" asp-route-id="@item.Id">&nbsp;<i class="glyphicon glyphicon-book"></i>&nbsp;</a>
            </td>
        </tr>
}
    </tbody>
</table>

StudyReg.Web/Pages/Decks/Manage.cshtml
@page
@model StudyReg.Web.Pages.Decks.ManageModel

@{
    ViewData["Title"] = "Manage Deck";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Manage Deck - @Html.DisplayFor(model => model.Deck.Title)</h2>
<span class="btn btn-success pull-right" type="button" data-toggle="modal" data-target="#myModal"><i class="glyphicon glyphicon-plus"></i>&nbsp;Add Card</span>
<h3>Cards</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DeckCards[0].Card.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeckCards[0].Card.Answer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var deckCard in Model.DeckCards)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => deckCard.Card.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => deckCard.Card.Answer)
                </td>
                <td>
                    <form method="post" asp-page-handler="delete">
                        <input type="hidden" name="cardId" value="@deckCard.CardId" />
                        <input type="hidden" name="deckId" value="@deckCard.DeckId" />
                        <button type="submit" class="btn btn-danger">
                            <i class="glyphicon glyphicon-trash"></i> 
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a class="btn btn-primary" asp-page="./Index"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;Decks</a>
</div>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Add Card</h4>
            </div>
            <div class="modal-body">
                <form method="post" asp-page-handler="add">
                    <input type="hidden" asp-for="Deck.Id" />
                    <input type="hidden" name="deckId" value="@Model.Deck.Id" />
                    <div class="form-group">
                        <label asp-for="DeckCards[0].Card.Title" class="control-label"></label>
                        <input name="cardTitle" class="form-control" />
                        <span asp-validation-for="DeckCards[0].Card.Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DeckCards[0].Card.Answer" class="control-label"></label>
                        <input name="cardAnswer" class="form-control" />
                        <span asp-validation-for="DeckCards[0].Card.Answer" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Add" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudyReg.Web/Pages/Decks/Study.cshtml
@page
@model StudyReg.Web.Pages.Decks.StudyModel
@{
    ViewData["Title"] = "Study";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<br />

@if (Model.Card == null)
{
    <div class="jumbotron" style="text-align:center">
        <div class="container">
            <h1>Study</h1>
            <p class="lead">Learn cards from @Html.DisplayFor(model => model.Deck.Title) using the Leitner System. Earlier stages should be studied more frequently, later stages less frequently.</p>
        </div>
    </div>

    <div class="row">
        @if (Model.Stages != null)
        {
            foreach (var stage in Model.Stages)
            {
                <div class="@(stage.Stage == 0 ? "col-md-2 col-md-offset-1" : "col-md-2")">
                    <div class="panel panel-default">
                        <div class="panel-heading"><h4>@(stage.Stage == 0 ? "Unstudied" : $"Stage {stage.Stage}")</h4></div>
                        <div class="panel-body">
                            <h4>@stage.Count Cards</h4>
                            @if (stage.Count > 0)
                            {
                            <form method="post" asp-page-handler="start">
                                <input type="hidden" name="deckId" value="@Model.Deck.Id" />
                                <input type="hidden" name="stage" value="@stage.Stage" />
                                <input type="hidden" name="numCards" value="@stage.Count" />
                                <button type="submit" class="btn btn-primary btn-lg">
                                    <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Study
                                </button>
                            </form>
                            }
                        </div>
                    </div>
                </div>
            }
        }
    </div>
}
else
{
    <div class="row" style="display:flex;align-items:center">
        <div class="col-sm-2">
            <label class="btn btn-primary btn-lg" id="cardFlip"><i class="glyphicon glyphicon-refresh"></i>&nbsp;Flip</label>
        </div>
        <div class="col-sm-10">
            <div class="jumbotron" style="text-align:center">
                <div class="container">
                    <div id="cardTitle">
                        <h1 style="font-size:8vw;">@Model.Card.Title</h1>
                    </div>
                    <div id="cardAnswer" style="display:none">
                        <h1 style="font-size:8vw;">@Model.Card.Answer</h1>
                    </div>
                </div>
            </div>
            <form id="cardSubmit" method="post" asp-page-handler="answer">
                <input type="hidden" name="deckId" value="@Model.Deck.Id" />
                <input type="hidden" name="cardId" value="@Model.Card.Id" />
                <input type="hidden" name="currentStage" value="@Model.Card." />
                <input id="cardResult" type="hidden" name="result" value="false" />
                <input id="cardResult" type="hidden" name="cardsLeft" value="@Model.Remaining" />
                <button id="correctButton" type="submit" class="btn btn-success btn-lg">
                    <i class="glyphicon glyphicon-check">&nbsp;Correct</i>
                </button>
                <button id="wrongButton" type="submit" class="btn btn-danger btn-lg">
                    <i class="glyphicon glyphicon-remove">&nbsp;Wrong</i>
                </button>
            </form>
        </div>
    </div>
}

<script>
    function flip () {
        if ($("#cardTitle").is(":hidden")) {
            $("#cardTitle").show();
            $("#cardAnswer").hide();
            $("#cardSubmit").hide();
        }
        else {
            $("#cardTitle").hide();
            $("#cardAnswer").show();
            $("#cardSubmit").show();
        }
    };

    $('#correctButton').click(function () {
        $('#cardResult').val("true");
    });

    $('#wrongButton').click(function () {
        $('#cardResult').val("false");
    });

    $('#cardAnswer').hide();
    $("#cardSubmit").hide();

    $('#cardFlip').click(flip);

    $(document).keydown(function (event) {
        let key = event.keyCode;
        switch (key) {
            case 32: //spacebar
                flip();
                break;
        }
    });
</script>